name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

      - name: Run pytest
        run: uv run pytest
